# -*- coding: utf-8 -*-
"""AD - Desafio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NFx-brKGdXuH4K7V5pTCCShbhUezfuVp
"""

causa_acidente = ['Falta de atenção à Condição', 'Desobediência às normas de trânsito pelo condutor', 'Ingestão de Álcool', 'Velocidade Incompatível' ]
classificacao_acidente = ['Com Vítimas Fatais', 'Sem Vítimas', 'Com Vítimas Feridas']
fase_dia = ['Amanhecer', 'Anoitecer', 'Plena Noite', 'Pleno Dia']
condicao_meteorologica = ['Chuva', 'Céu Claro', 'Nublado', 'Sol']

print('Estas são algumas causas de acidentes de trânsito:', '\n', causa_acidente, '\n')
print('Estas são algumas classificações em relação as vítimas dos acidentes de trânsito: ', '\n', classificacao_acidente, '\n')
print('Estas são as fases do dia em que ocorreram os acidentes de trânsito: ', '\n', fase_dia, '\n')
print('Estas são as condições meteorologicas no dia dos acidentes de trânsito: ', '\n', condicao_meteorologica, '\n')
causa_acidente.extend(classificacao_acidente)
print('Relacionado ao acidente: ', causa_acidente, '\n')
fase_dia.extend(condicao_meteorologica)
print('Relacionado ao dia do acidente: ', fase_dia)